### ISSUE TITLE
thread factory of version2 not works as expected

### ISSUE THREAD

**Issue by cheneydeng** [chenshuo/recipes#12]
hi, I'm reading your book about the "muduo". And seems found some issue,the version 2 of the thread factory haven't put the newly created stock into the map,the reason is that the pStock will be deconstructed when it leaves "get" function.Here is your [code:](https://github.com/chenshuo/recipes/blob/master/thread/test/Factory.cc)

I wrote a test and this test will output twice "hello NOT EXIST"

```#include <map>
#include <string>
#include <memory>
#include <iostream>

class Stock {
public:
    Stock(const std::string &) {}
};


//if pStock defined as a global variable,it will be ok.
class StockFactory// : std::noncopyable
{
public:
    std::shared_ptr<Stock> get(const std::string& key)
    {
        std::shared_ptr<Stock> pStock;
        std::weak_ptr<Stock>& wkStock = stocks_[key];
        pStock = wkStock.lock();
        if (!pStock)
        {
            std::cout << key << " NOT EXIST" << std::endl;
            pStock.reset(new Stock(key));
            wkStock = pStock;
        } else {
            std::cout << key << " EXIST" << std::endl;
        }
        return pStock;
    }

private:
    std::map<std::string, std::weak_ptr<Stock> > stocks_;
};

int main() {

    StockFactory f;
    f.get("hello");
    f.get("hello");
}
```

**Comment by chenshuo** [comment]
Because you didn't save the return value of get() to a shared_ptr.
This is the exact purpose of version 2: if no one use the value, the factory won't keep it.
