### ISSUE TITLE
Need your help with 3 questions

### ISSUE THREAD

**Issue by happy42779** [chenshuo/recipes#14]
Hi, 
Thank you for sharing your code. I'm learning your code, and try to adopt your code into my program.
I'm writing the client by Qt on 64 bit windows, and server on 64 bit linuxMint, As I used your code in "codec.h", I sent information from client to server, 
1. As I send the buf and received the buf on server end, as muduo::net::Buffer*, then retrieveAllAsString, I get a muduo::string, somehow, I try to get a std::string version by: std::string msg(muduostring.c_str()); I would get a empty string.
2. If I copy all bytes showed in debugger after encoding finishes, then use a Socket tool to send them to server, then I can get a normal msg(not empty), but the length would be shorter than the length showed in muduo::net::Buffer, seemed like 8 less in length.
3. after passing the msg I got to the decode function, it never get the same checksum calculated out as what it read from the package.

**Comment by happy42779** [comment]
Thanks for your code very much, and the problems i met have been already solved. 
1. I used memory copy instead, since the original buffer type within these two strings are the same, so it worked.
2&3 These two problems were resulted in the wrong decode() function in the code I saw. The length in decode() was taken less than the the original length while encoding it.

**Comment by Lotus253** [comment]
possible you have '\0' (or similar) in the you string. I think need serialise your object to 'byte' before encoding.
