### ISSUE TITLE
recipes/algorithm/combination.cc

### ISSUE THREAD

**Issue by fyzhr** [chenshuo/recipes#15]
"next_permutation" works on a sorted-array, but (L10) int elements[] = { 1, 1, 1, 0, 0, 0, 0 }; this is not a non-decreasing array,so the answer will output only one line : "1:1,2,3".

I think elements should be "{0, 0, 0, 1, 1, 1, 1}" and (L21) should be "if (!selectors[i])", that will work and output results as except.

**Comment by chenshuo** [comment]
Have you run the code?
The code uses prev_permutation, not next_permutation.

**Comment by fyzhr** [comment]
Oh, so stupid that confuse prev_permutation with next_permutation
