### ISSUE TITLE
关于吞吐量的疑问

### ISSUE THREAD

**Issue by xiaojingxie** [chenshuo/recipes#24]
请教一下，
https://blog.csdn.net/Solstice/article/details/5864889

这篇提到的吞吐量数据，为啥千兆网卡的吞吐量可以达到几百MB呢？带宽不是只有128MB吗？

**Comment by xiaojingxie** [comment]
> 测试内容为：客户端与服务器运行在同一台机器，均为单线程，测试并发连接数为 1/10/100/1000/10000 时的吞吐量。
> 
> 在同一台机器测试吞吐量的原因：
> 
> ## 现在的 CPU 很快，即便是单线程单 TCP 连接也能把 Gigabit 以太网的带宽跑满。如果用两台机器，所有的吞吐量测试结果都将是 100 MiB/s，失去了对比的意义。（或许可以对比哪个库占的 CPU 少。）
> 在同一台机器上测试，可以在 CPU 资源相同的情况下，单纯对比网络库的效率。也就是说单线程下，服务端和客户端各占满 1 个 CPU，比较哪个库的吞吐量高。
> 作者：陈硕
> 来源：CSDN
> 原文：https://blog.csdn.net/Solstice/article/details/5864889
> 版权声明：本文为博主原创文章，转载请附上博文链接！

不好意思，可能我没描述清楚，我的问题**不是**为什么要在一台机器上测试。而是：
**为啥千兆网卡的吞吐量可以达到几百MB呢？**

:)

**Comment by wzhe** [comment]
Linux中本机和本机Socket通信会走网卡吗？
先说结论：**不走网卡，不走物理设备，但是走虚拟设备，loopback device环回.**  本机的报文的路径是这样的：应用层-> socket接口 -> 传输层（tcp/udp报文） -> 网络层 -> back to 传输层 -> backto socket接口 -.> 传回应用程序在网络层，会在路由表查询路由，路由表（软件路由，真正的转发需要依靠硬件路由，这里路由表包括快速转发表和FIB表）初始化时会保存主机路由(host route，or 环回路由)， 查询（先匹配mask，再匹配ip，localhost路由在路由表最顶端，最优先查到）后发现不用转发就不用走中断，不用发送给链接层了，不用发送给网络设备（网卡）。像网卡发送接收报文一样，走相同的接收流程，只不过net device是loopback device，最后发送回应用程序。这一套流程当然和转发和接收外网报文一样，都要经过内核协议栈的处理，不同的是本机地址不用挂net device.

作者：王小陆
链接：https://www.zhihu.com/question/43590414/answer/96246937
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。


另外，陈硕之前有在微博中说过，不要在issue中提自己的问题，issue只是用来反馈相关代码bug使用的。
在得到解答后，把你这个issue关了吧。另外，善用搜索引擎，可以帮你节省大量时间

**Comment by xiaojingxie** [comment]
多谢解惑。
