### ISSUE TITLE
recipes/reactor 中所有例子 make 之后显示  error 如下： ambigous ？？？？

### ISSUE THREAD

**Issue by DPSDL** [chenshuo/recipes#29]
g++ -O0 -g  -Wall -I ../.. -pthread -o test1 Channel.cc EventLoop.cc Poller.cc ../../logging/Logging.cc ../../logging/LogStream.cc ../../thread/Thread.cc ../../datetime/Timestamp.cc test1.cc -lpthread
../../thread/Thread.cc: In function ‘pid_t muduo::CurrentThread::tid()’:
../../thread/Thread.cc:103:26: error: call of overloaded ‘gettid()’ is ambiguous
  103 |     t_cachedTid = gettid();
      |                          ^
In file included from /usr/include/unistd.h:1170,
                 from /usr/include/boost/config/stdlib/libstdcpp3.hpp:78,
                 from /usr/include/boost/config.hpp:49,
                 from /usr/include/boost/core/noncopyable.hpp:12,
                 from /usr/include/boost/noncopyable.hpp:15,
                 from ../../thread/Atomic.h:11,
                 from ../../thread/Thread.h:11,
                 from ../../thread/Thread.cc:8:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: candidate: ‘__pid_t gettid()’
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
../../thread/Thread.cc:30:7: note: candidate: ‘pid_t {anonymous}::gettid()’
   30 | pid_t gettid()
      |       ^~~~~~
make: *** [../reactor.mk:6: test1] Error 1

**Comment by chenshuo** [comment]
`gettid(2)` was added in glibc 2.30, so you may just remove the `getpid()` from `Thread.cc`.

Ref. http://man7.org/linux/man-pages/man2/gettid.2.html

**Comment by DPSDL** [comment]
Thank you very much for your reply, I changed Thread.cc gettid() to gettid(2), the problem is solved
