### ISSUE TITLE
Mac OS 下 如何 替代Thread.cc 中的头文件，<sys/prctl.h>,<linux/unistd.h>

### ISSUE THREAD

**Issue by To-be-or-not** [chenshuo/recipes#30]
您好，
     我是您 《Linux多线程》 的读者，我遇到一个问题：
     我用的是Mac OS 系统，还是个新手，当我编译的时候，有个报错，说<sys/prctl.h> 找不到。 我查了一下，有人说这个文件在Mac OS 下是不支持的。 请问您有什么建议吗，是不是我弄的有问题？
     非常感谢！

**Comment by wzhe** [comment]
这本书的背景是服务器环境，还是装个linux虚拟机进行学习吧。

**Comment by To-be-or-not** [comment]
嗯嗯，好的，多谢了！
