### ISSUE TITLE
does the Object of data has member function of clean()?

### ISSUE THREAD

**Issue by justnull** [chenshuo/recipes#33]
https://github.com/chenshuo/recipes/blob/b9b67c9b05857c2f5a47d91bbc8be93d123e1cbc/thread/SignalSlot.h#L85

**Comment by justnull** [comment]
我不明白C++头文件如何编译来测试语法错误？我问的问题可能比较基础，请大佬见谅。

**Comment by chenshuo** [comment]
一般的做法是对 head-only 的 library 写单元测试，这样就能编译并检查语法错，更重要的是，还能验证功能是否正确。

**Comment by justnull** [comment]
那data作为SlotImpl的成员变量，怎么可以调用SlotImpl的成员函数clean？

**Comment by justnull** [comment]
因为习惯了Java 一个类一个文件，现在看一个文件多个类的C++眼都容易花。
